name: Automated Testing

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.16'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Tests with Coverage
        run: npm run test:coverage

      # Generate Coverage Report
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          annotations: none

      # Comment the Coverage Report on PR
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

      - name: Check Coverage
        run: |
          COVERAGE=$(npx coverage-summary-logger < coverage/lcov.info | grep 'All files' | awk '{print $4}' | sed 's/%//')
          if [ "$COVERAGE" -lt 75 ]; then
            echo "Error: Code coverage is below 75%."
            exit 1
          fi
