name: Automated Testing

on:
  pull_request:
    branches: ["*"]

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18.16"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      #Run test coverage
      - name: Run Tests with Coverage
        run: npm run test:coverage

      # Generate Coverage Report
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          annotations: none

      # Comment the Coverage Report on PR
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        with:
          files: "coverage/report.xml"
